2024-07-09 12:22:56,615 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Configure stats pid to 1164586
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Loading settings from /home/se2422/.config/wandb/settings
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Loading settings from /scratch/se2422/NRC-regularizations/wandb/settings
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main/exp/case1/regs.py', 'program_abspath': '/scratch/se2422/NRC-regularizations/main/exp/case1/regs.py', 'program': '/scratch/se2422/NRC-regularizations/main/exp/case1/regs.py'}
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_init.py:_log_setup():520] Logging user logs to /scratch/se2422/NRC-regularizations/wandb/run-20240709_122256-6879ccb1-218c-44c3-a9f1-df2d132d18e6/logs/debug.log
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_init.py:_log_setup():521] Logging internal logs to /scratch/se2422/NRC-regularizations/wandb/run-20240709_122256-6879ccb1-218c-44c3-a9f1-df2d132d18e6/logs/debug-internal.log
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_init.py:init():560] calling init triggers
2024-07-09 12:22:56,616 INFO    MainThread:1164586 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'device': 'cpu', 'env': 'reacher', 'seed': 0, 'eval_freq': 100, 'max_epochs': 12000, 'checkpoints_path': None, 'load_model': '', 'batch_size': 256, 'num_eval_batch': 100, 'data_size': 1000, 'normalize': 'none', 'arch': '256-R-256-R-256-R|T', 'optimizer': 'sgd', 'regularization': 'l1', 'dropout_probability': 0.5, 'lamH': -1, 'lamW': 0.01, 'lr': 0.01, 'mode': 'null', 'data_folder': './dataset/mujoco', 'project': 'NC_explore', 'group': 'reg-l1', 'name': 'Ereacher_DS1000_wd0.01_Eps12000_Reg-l1'}
2024-07-09 12:22:56,617 INFO    MainThread:1164586 [wandb_init.py:init():610] starting backend
2024-07-09 12:22:56,617 INFO    MainThread:1164586 [wandb_init.py:init():614] setting up manager
2024-07-09 12:22:56,618 INFO    MainThread:1164586 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-09 12:22:56,622 INFO    MainThread:1164586 [wandb_init.py:init():622] backend started and connected
2024-07-09 12:22:56,628 INFO    MainThread:1164586 [wandb_init.py:init():711] updated telemetry
2024-07-09 12:22:56,656 INFO    MainThread:1164586 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-07-09 12:22:57,280 INFO    MainThread:1164586 [wandb_run.py:_on_init():2402] communicating current version
2024-07-09 12:22:57,339 INFO    MainThread:1164586 [wandb_run.py:_on_init():2411] got version response upgrade_message: "wandb version 0.17.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-07-09 12:22:57,339 INFO    MainThread:1164586 [wandb_init.py:init():795] starting run threads in backend
2024-07-09 12:23:00,698 INFO    MainThread:1164586 [wandb_run.py:_console_start():2380] atexit reg
2024-07-09 12:23:00,698 INFO    MainThread:1164586 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2024-07-09 12:23:00,698 INFO    MainThread:1164586 [wandb_run.py:_redirect():2300] Wrapping output streams.
2024-07-09 12:23:00,698 INFO    MainThread:1164586 [wandb_run.py:_redirect():2325] Redirects installed.
2024-07-09 12:23:00,702 INFO    MainThread:1164586 [wandb_init.py:init():838] run started, returning control to user process
2024-07-09 12:23:07,699 WARNING MsgRouterThr:1164586 [router.py:message_loop():77] message_loop has been closed
